name = "kilostash"
compatibility_date = "2025-07-01"
main = "src/index.ts"

routes = [
  { pattern = "cloud.lexa.web.id/*", zone_name = "lexa.web.id" }
]

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "kilostash"

[[kv_namespaces]]
binding = "KV"
id = "d6fb2c14bf3147a2a5ec3c9bd48bbe5b"
